apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd # ArgoCD will manage this installation
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts' # The official global chart registry
    chart: kube-prometheus-stack
    targetRevision: 62.0.0 # Locks the specific version so your deployment never breaks unexpectedly
  destination:
    server: 'https://kubernetes.default.svc' # Installs it directly into our live EKS cluster
    namespace: monitoring # Places all monitoring tools in their own isolated namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true # Tells ArgoCD to create the 'monitoring' folder inside Kubernetes if it doesn't exist
