plugin: aws_ec2
regions:
  - eu-west-3 # Must match your Terraform region

# Group the servers dynamically based on the "Role" tag we created in Terraform
keyed_groups:
  - key: tags.Role
    prefix: role